name: Test E2E

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get node version from volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@main

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Docker Compose Build
        run: pnpm run docker:e2e:build

      - name: Docker Compose Up As E2E Testing
        run: pnpm run docker:e2e:ci
